[workspace]
authors = ["Cauchyyyyy <124767414+Cauchyyyyy@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "NPDE-24-Fall"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.3.3,<3"
matplotlib = ">=3.10.6,<4"
python = ">=3.13.7,<3.14"
ipykernel = ">=6.30.1,<7"
